theme: minima
title: TheJooosh - Powershell, Python, and more.
author: TheJooosh
description: A blog that sweeps various programming & system administration topics for both the on-premesis and cloud worlds.
